CREATE TABLE "ORO_TEST_2"
   (	"ID" NUMBER,
	"DESCRIPTION" VARCHAR2(20),
	"NAME" VARCHAR2(30),
	"PRENAME" VARCHAR2(30),
	"CITY_NO" NUMBER,
	 CONSTRAINT "PK_ORO_TEST_2" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ORO_TEST_2" FOREIGN KEY ("CITY_NO")
	  REFERENCES "ORO_TEST_3" ("ID") ENABLE
   ) ;

